-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWhO9WmcFXj1cu3wyTNvwXOCX/N2jSk+bkcARFsAxxlygCgYIKoZIzj0DAQehRANCAARrcnVPDcoYGmYjtxZj8ipG7/SfjpnfstY/y7zmgxYU//x8vWJtl+tfZc3SALWzby3PNraGGGxq2Ym5g6/EbdzE
-----END PRIVATE KEY-----