-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWtHsmRYGKDqbv716
a2m7xQGhiErbS83/jjKVLZFFooKgCgYIKoZIzj0DAQehRANCAAQtpOQayHFS/0wP
ZTt8SPmESzInCOre6GXvQdKtnraGgOu5xC0GX4cTmekIGT2Azl2djZb+lfTSY+15
MCbm1iA3
-----END PRIVATE KEY-----